name: Check Updates

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Every Day at 01:00 UTC

jobs:
  check-updates:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v4
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # ratchet:actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install --global npm-check-updates
          npx ncu --verbose
